apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager.io/v1alpha2
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brunostel@gmail.com
    privateKeySecretRef:
      name: letsencrypt-tls
    solvers:
      - htpp01:
          ingress:
            class: nginx