apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce #Pode gravar, ler, desde que estejamos dentro do mesmo node que está alocado o storage
  storageClassName: local-device

